export const editApplicationConfig = [
    {
      head: "ES_TITILE_APPLICANT_DETAILS",
      body: [
        {
          route: "area-mapping",
          component: "AreaMapping",
          withoutLabel: true,
          key: "areaMapping",
          type: "component",
          nextStep: "applicant-details",
          hideInEmployee: true,
          isMandatory: true,
          texts: {
            header:"BPA_AREA_MAPPING",
            submitBarLabel: "CS_COMMON_NEXT",
          },
        },
        {
          route: "applicant-details",
          component: "ApplicantDetails",
          withoutLabel: true,
          key: "applicant",
          type: "component",
          nextStep: "address-details",
          hideInEmployee: true,
          isMandatory: true,
          texts: {
            header:"APPLICANT_PERSONAL_DETAILS",
            submitBarLabel: "CS_COMMON_NEXT",
          },
        },
        {
          route: "address-details",
          component: "AddressDetails",
          withoutLabel: true,
          key: "address",
          type: "component",
          nextStep: "land-details",
          hideInEmployee: true,
          isMandatory: true,
          texts: {
            submitBarLabel: "CS_COMMON_NEXT",
          },
        },
        {
            route: "land-details",
            component: "LandDetails",
            withoutLabel: true,
            key: "land",
            type: "component",
            nextStep: "document-details",
            hideInEmployee: true,
            isMandatory: true,
            texts: {
              header:"APPLICANT_LAND_DETAILS",
              submitBarLabel: "CS_COMMON_NEXT",
            },
        },
        {
            route: "document-details",
            component: "DocumentDetails",
            withoutLabel: true,
            key: "documents",
            type: "component",
            nextStep: "form22A",
            hideInEmployee: true,
            isMandatory: true,
            texts: {
              header:"APPLICANT_DOCUMENT_DETAILS",
              submitBarLabel: "CS_COMMON_NEXT",
            },
        },
        {
            route: "form22A",
            component: "Form22A",
            withoutLabel: true,
            key: "form",
            type: "component",
            nextStep: "form23A",
            hideInEmployee: true,
            isMandatory: true,
            texts: {
              header:"APPLICANT_FORM23A_DETAILS",
              submitBarLabel: "CS_COMMON_NEXT",
            },
        },
        {
            route: "form23A",
            component: "Form23A",
            withoutLabel: true,
            key: "form23A",
            type: "component",
            nextStep: "form23B",
            hideInEmployee: true,
            isMandatory: true,
            texts: {
              header:"APPLICANT_FORM23A_DETAILS",
              submitBarLabel: "CS_COMMON_NEXT",
            },
        },
        {
            route: "form23B",
            component: "Form23B",
            withoutLabel: true,
            key: "form23B",
            type: "component",
            nextStep: null,
            hideInEmployee: true,
            isMandatory: true,
            texts: {
              header:"APPLICANT_FORM23B_DETAILS",
              submitBarLabel: "CS_COMMON_NEXT",
            },
        }
      ],
    },
  ];